"""
test_phase11.py — Phase 11 Verification Script

Run this script to confirm that:
    1. The NotesGenerator can fetch extended context for a topic.
    2. The LLM successfully synthesizes this into formatted study notes.

How to run:
    cd "g:\\AI Learning Companion"
    .\\venv\\Scripts\\Activate.ps1
    python test_phase11.py
"""

from __future__ import annotations

import sys

from src.notes_generator import NotesGenerator
from src.utils import load_settings


def print_header(title: str) -> None:
    """Print a formatted section header."""
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")


def test_notes_generator() -> bool:
    """Step 1: Test Study Notes functionality."""
    print_header("Step 1: Study Notes Generation")
    settings = load_settings()
    generator = NotesGenerator(settings)
    
    # We rely on the mock data (biology/physics facts) inserted during test_phase9.py
    topic = "Fundamental Biology and Physics Principles"

    try:
        print(f"  Topic: '{topic}'")
        print("  Retrieving extended context and generating notes (this may take up to 30 seconds)...")
        
        notes = generator.generate_notes(topic)
        
        print("\n" + "=" * 40)
        print("  GENERATED NOTES PREVIEW")
        print("=" * 40)
        print(notes)
        print("=" * 40 + "\n")
        
        # Check for expected formatting and content
        if not notes or "I couldn't find" in notes:
            print("  [FAIL] Failed to generate notes or find context.")
            return False
            
        has_markdown = "#" in notes or "-" in notes or "*" in notes
        has_content = "mitochondria" in notes.lower() or "gravity" in notes.lower() or "photosynthesis" in notes.lower()
        
        if has_markdown and has_content:
            print("  [PASS] Notes were successfully generated with expected formatting and content.")
            return True
        else:
            print("  [FAIL] Notes lacked expected formatting or content.")
            return False

    except Exception as exc:
        print(f"  [FAIL] Exception during notes generation: {exc}")
        return False


def main() -> None:
    """Run all Phase 11 verification tests."""
    # Force UTF-8 encoding for standard output to prevent crash when LLM generates emojis
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    
    print("\nAI Learning Companion — Phase 11 Notes Generator Test")
    
    print("  Note: This test relies on the FAISS data generated by test_phase9.py.")

    results = [
        test_notes_generator(),
    ]

    print_header("Summary")
    passed = sum(results)
    total = len(results)
    print(f"  Tests passed: {passed}/{total}")

    if all(results):
        print("\n  Phase 11 COMPLETE — The Study Notes Generator is ALIVE!")
        print("  Next: Phase 12 — Flashcard Generator\n")
    else:
        print("\n  Some tests failed. Fix the issues above and re-run.\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
