"""
test_phase10.py — Phase 10 Verification Script

Run this script to confirm that:
    1. The QAEngine correctly orchestrates retrieval and LLM generation.
    2. The LLM accurately answers a question using the retrieved context.
    3. The LLM correctly refuses to answer when the context is insufficient.

How to run:
    cd "g:\\AI Learning Companion"
    .\\venv\\Scripts\\Activate.ps1
    python test_phase10.py
"""

from __future__ import annotations

import sys

from src.qa_engine import QAEngine
from src.utils import load_settings


def print_header(title: str) -> None:
    """Print a formatted section header."""
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")


def test_qa_engine() -> bool:
    """Step 1: Test Question Answering functionality."""
    print_header("Step 1: RAG Question Answering")
    settings = load_settings()
    qa_engine = QAEngine(settings)
    
    # We rely on the mock data (biology/physics facts) inserted during test_phase9.py
    
    query_success = "What is the powerhouse of the cell?"
    query_fail = "What is the capital of Japan?"

    all_passed = True

    try:
        # Test 1: Question that exists in the context
        print(f"  Test A - Contextual Query : '{query_success}'")
        print("  Generating answer (this may take a few seconds)...")
        answer1 = qa_engine.answer_question(query_success)
        print(f"  Answer: {answer1}\n")
        
        if "mitochondria" in answer1.lower():
            print("  [PASS] The LLM correctly answered using the context.")
        else:
            print("  [FAIL] The LLM failed to identify 'mitochondria'.")
            all_passed = False

        # Test 2: Question that does NOT exist in the context
        print(f"  Test B - Out-of-Bounds Query : '{query_fail}'")
        print("  Generating answer (this may take a few seconds)...")
        answer2 = qa_engine.answer_question(query_fail)
        print(f"  Answer: {answer2}\n")
        
        # Checking if it refused gracefully based on our prompt instructions
        if "cannot answer" in answer2.lower() or "tokyo" not in answer2.lower():
            print("  [PASS] The LLM successfully refused to answer out-of-context question.")
        else:
            print("  [FAIL] The LLM hallucinated an answer instead of refusing!")
            all_passed = False

        return all_passed

    except Exception as exc:
        print(f"  [FAIL] Exception during QA generation: {exc}")
        return False


def main() -> None:
    """Run all Phase 10 verification tests."""
    print("\nAI Learning Companion — Phase 10 QA Engine Test")
    
    print("  Note: This test relies on the FAISS data generated by test_phase9.py.")

    results = [
        test_qa_engine(),
    ]

    print_header("Summary")
    passed = sum(results)
    total = len(results)
    print(f"  Tests passed: {passed}/{total}")

    if all(results):
        print("\n  Phase 10 COMPLETE — The Full RAG Pipeline is ALIVE!")
        print("  Next: Phase 11 — Study Notes Generator\n")
    else:
        print("\n  Some tests failed. Fix the issues above and re-run.\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
