"""
test_phase13.py — Phase 13 Verification Script

Run this script to confirm that:
    1. The QuizGenerator queries the RAG pipeline.
    2. The LLM successfully generates a complex JSON array with multiple-choice structures.
    3. The JSON is parsed into Python dicts correctly.

How to run:
    cd "g:\\AI Learning Companion"
    .\\venv\\Scripts\\Activate.ps1
    python test_phase13.py
"""

from __future__ import annotations

import sys

from src.quiz_generator import QuizGenerator
from src.utils import load_settings


def print_header(title: str) -> None:
    """Print a formatted section header."""
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")


def test_quiz_generator() -> bool:
    """Step 1: Test JSON Quiz Generation."""
    print_header("Step 1: Structured Quiz Generation")
    settings = load_settings()
    generator = QuizGenerator(settings)
    
    # We rely on the mock data inserted during test_phase9.py
    topic = "Physics and Biology Facts"
    count = 2

    try:
        print(f"  Topic: '{topic}'")
        print(f"  Requested Count: {count}")
        print("  Generating structured JSON quiz (this may take 20-40 seconds)...")
        
        quiz = generator.generate_quiz(topic, count=count)
        
        print("\n" + "=" * 40)
        print("  PARSED QUIZ PREVIEW")
        print("=" * 40)
        
        if not quiz:
            print("  [FAIL] No quiz data was returned.")
            return False
            
        for i, q in enumerate(quiz, 1):
            print(f"  Question {i}: {q.get('question', 'MISSING QUESTION')}")
            options = q.get('options', [])
            for j, opt in enumerate(options):
                # Using letters A, B, C, D
                print(f"    {chr(65+j)}. {opt}")
            print(f"\n  Answer     : {q.get('answer', 'MISSING ANSWER')}")
            print(f"  Explanation: {q.get('explanation', 'MISSING EXPLANATION')}\n")
            print("-" * 40)
            
        print("=" * 40 + "\n")
        
        # Verify the structure and content
        if len(quiz) == count:
            print(f"  [PASS] Successfully generated and parsed {count} quiz questions.")
            
            # Check for hallucination or error
            first_q = quiz[0]
            expected_keys = ["question", "options", "answer", "explanation"]
            
            if all(k in first_q for k in expected_keys) and len(first_q.get("options", [])) == 4 and "Error" not in first_q.get("question", ""):
                 print("  [PASS] Quiz questions possess the correct complex dict keys and 4 options.")
                 return True
            else:
                 print("  [FAIL] Quiz questions lacked proper keys, options, or returned an error.")
                 return False
        else:
            print(f"  [FAIL] Expected {count} questions, but parsed {len(quiz)}.")
            return False

    except Exception as exc:
        print(f"  [FAIL] Exception during quiz generation: {exc}")
        return False


def main() -> None:
    """Run all Phase 13 verification tests."""
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    
    print("\nAI Learning Companion — Phase 13 Quiz Generator Test")
    print("  Note: This test relies on the FAISS data generated by test_phase9.py.")

    results = [
        test_quiz_generator(),
    ]

    print_header("Summary")
    passed = sum(results)
    total = len(results)
    print(f"  Tests passed: {passed}/{total}")

    if all(results):
        print("\n  Phase 13 COMPLETE — The Quiz Generator successfully outputs complex JSON structures!")
        print("  Next: Phase 14 — Study Planner\n")
    else:
        print("\n  Some tests failed. Fix the issues above and re-run.\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
