"""
test_phase12.py — Phase 12 Verification Script

Run this script to confirm that:
    1. The FlashcardGenerator queries the RAG pipeline.
    2. The LLM's response is successfully parsed from JSON into Python dicts.

How to run:
    cd "g:\\AI Learning Companion"
    .\\venv\\Scripts\\Activate.ps1
    python test_phase12.py
"""

from __future__ import annotations

import sys

from src.flashcard_generator import FlashcardGenerator
from src.utils import load_settings


def print_header(title: str) -> None:
    """Print a formatted section header."""
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")


def test_flashcard_generator() -> bool:
    """Step 1: Test JSON Flashcard Generation."""
    print_header("Step 1: Structured Flashcard Generation")
    settings = load_settings()
    generator = FlashcardGenerator(settings)
    
    # We rely on the mock data inserted during test_phase9.py
    topic = "Physics and Biology"
    count = 3

    try:
        print(f"  Topic: '{topic}'")
        print(f"  Requested Count: {count}")
        print("  Generating structured JSON (this may take 15-30 seconds)...")
        
        flashcards = generator.generate_flashcards(topic, count=count)
        
        print("\n" + "=" * 40)
        print("  PARSED FLASHCARDS PREVIEW")
        print("=" * 40)
        
        if not flashcards:
            print("  [FAIL] No flashcards were returned.")
            return False
            
        for i, card in enumerate(flashcards, 1):
            print(f"  Card {i}:")
            print(f"    Front (Q): {card.get('front', 'MISSING FRONT')}")
            print(f"    Back (A) : {card.get('back', 'MISSING BACK')}\n")
            
        print("=" * 40 + "\n")
        
        # Verify the structure and content
        if len(flashcards) == count:
            print(f"  [PASS] Successfully generated and parsed {count} flashcards.")
            
            # Check for hallucination or error
            first_card = flashcards[0]
            if "front" in first_card and "back" in first_card and "Error" not in first_card.get("front", ""):
                 print("  [PASS] Flashcards possess the correct dict keys.")
                 return True
            else:
                 print("  [FAIL] Flashcards lacked proper keys or returned an error card.")
                 return False
        else:
            print(f"  [FAIL] Expected {count} flashcards, but parsed {len(flashcards)}.")
            return False

    except Exception as exc:
        print(f"  [FAIL] Exception during flashcard generation: {exc}")
        return False


def main() -> None:
    """Run all Phase 12 verification tests."""
    # Force UTF-8 encoding for standard output just in case
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    
    print("\nAI Learning Companion — Phase 12 Flashcard Generator Test")
    print("  Note: This test relies on the FAISS data generated by test_phase9.py.")

    results = [
        test_flashcard_generator(),
    ]

    print_header("Summary")
    passed = sum(results)
    total = len(results)
    print(f"  Tests passed: {passed}/{total}")

    if all(results):
        print("\n  Phase 12 COMPLETE — The Flashcard Generator successfully outputs structured JSON!")
        print("  Next: Phase 13 — Quiz Generator\n")
    else:
        print("\n  Some tests failed. Fix the issues above and re-run.\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
