"""
test_phase14.py — Phase 14 Verification Script

Run this script to confirm that:
    1. The StudyPlanner can fetch extended context for a topic.
    2. The LLM successfully synthesizes this into a multi-day Markdown schedule.

How to run:
    cd "g:\\AI Learning Companion"
    .\\venv\\Scripts\\Activate.ps1
    python test_phase14.py
"""

from __future__ import annotations

import sys

from src.study_planner import StudyPlanner
from src.utils import load_settings


def print_header(title: str) -> None:
    """Print a formatted section header."""
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")


def test_study_planner() -> bool:
    """Step 1: Test Study Planner functionality."""
    print_header("Step 1: Multi-day Study Plan Generation")
    settings = load_settings()
    planner = StudyPlanner(settings)
    
    # We rely on the mock data (biology/physics facts) inserted during test_phase9.py
    topic = "Fundamental Science Concepts"
    days = 3

    try:
        print(f"  Topic: '{topic}'")
        print(f"  Days : {days}")
        print("  Retrieving extended context and generating schedule (this may take up to 30 seconds)...")
        
        plan = planner.generate_plan(topic, days=days)
        
        print("\n" + "=" * 40)
        print("  GENERATED STUDY PLAN PREVIEW")
        print("=" * 40)
        print(plan)
        print("=" * 40 + "\n")
        
        # Check for expected formatting and content
        if not plan or "I couldn't find" in plan:
            print("  [FAIL] Failed to generate plan or find context.")
            return False
            
        # Verify it created entries for multiple days
        has_day_markers = "Day 1" in plan and "Day 2" in plan
        has_content = "mitochondria" in plan.lower() or "gravity" in plan.lower() or "photosynthesis" in plan.lower()
        
        if has_day_markers and has_content:
            print("  [PASS] Plan was successfully generated with expected day breakdowns and content.")
            return True
        else:
            print("  [FAIL] Plan lacked expected day markers or content.")
            return False

    except Exception as exc:
        print(f"  [FAIL] Exception during plan generation: {exc}")
        return False


def main() -> None:
    """Run all Phase 14 verification tests."""
    # Force UTF-8 encoding for standard output to prevent crash when LLM generates emojis
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    
    print("\nAI Learning Companion — Phase 14 Study Planner Test")
    
    print("  Note: This test relies on the FAISS data generated by test_phase9.py.")

    results = [
        test_study_planner(),
    ]

    print_header("Summary")
    passed = sum(results)
    total = len(results)
    print(f"  Tests passed: {passed}/{total}")

    if all(results):
        print("\n  Phase 14 COMPLETE — The Study Planner generates multi-day schedules!")
        print("  Next: Phase 15 — Chat Memory\n")
    else:
        print("\n  Some tests failed. Fix the issues above and re-run.\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
