"""
test_phase15.py — Phase 15 Verification Script

Run this script to confirm that:
    1. The ChatEngine can successfully process a multi-turn conversation.
    2. The LLM remembers context from previous turns (e.g., resolving pronouns).

How to run:
    cd "g:\\AI Learning Companion"
    .\\venv\\Scripts\\Activate.ps1
    python test_phase15.py
"""

from __future__ import annotations

import sys
import time

from src.chat_engine import ChatEngine
from src.utils import load_settings


def print_header(title: str) -> None:
    """Print a formatted section header."""
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")


def test_chat_memory() -> bool:
    """Step 1: Test multi-turn conversational memory."""
    print_header("Step 1: Stateful Conversation")
    settings = load_settings()
    engine = ChatEngine(settings)
    
    # We rely on the mock data inserted during test_phase9.py
    
    # Turn 1: Establish context
    turn1_query = "What is the powerhouse of the cell?"
    try:
        print(f"  [Turn 1] User: {turn1_query}")
        print("  Waiting for AI response...")
        turn1_response = engine.chat(turn1_query)
        print(f"  [Turn 1] AI  : {turn1_response.strip()}\n")
        
        if "mitochondria" not in turn1_response.lower():
             print("  [FAIL] AI failed to answer the base question correctly.")
             return False
             
        # Small delay to ensure clean console output
        time.sleep(1)
        
        # Turn 2: Follow up using a pronoun ("that")
        # If memory fails, the LLM won't know what "that" means.
        turn2_query = "Can you explain what that is used for?"
        print(f"  [Turn 2] User: {turn2_query}")
        print("  Waiting for AI response (using memory context)...")
        turn2_response = engine.chat(turn2_query)
        print(f"  [Turn 2] AI  : {turn2_response.strip()}\n")
        
        # The AI should talk about energy, power, or ATP regarding mitochondria
        if "energy" in turn2_response.lower() or "power" in turn2_response.lower() or "mitochondria" in turn2_response.lower():
             print("  [PASS] AI successfully remembered the context from Turn 1!")
             return True
        else:
             print("  [FAIL] AI did not seem to remember we were talking about mitochondria.")
             return False

    except Exception as exc:
        print(f"  [FAIL] Exception during chat: {exc}")
        return False


def main() -> None:
    """Run all Phase 15 verification tests."""
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    
    print("\nAI Learning Companion — Phase 15 Chat Memory Test")
    print("  Note: This test relies on the FAISS data generated by test_phase9.py.")

    results = [
        test_chat_memory(),
    ]

    print_header("Summary")
    passed = sum(results)
    total = len(results)
    print(f"  Tests passed: {passed}/{total}")

    if all(results):
        print("\n  Phase 15 COMPLETE — The AI remembers what we're talking about!")
        print("  Next: Phase 16 — UI Improvements (Streamlit)\n")
    else:
        print("\n  Some tests failed. Fix the issues above and re-run.\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
